// <auto-generated />
using System;
using DnDInventorySystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DnDInventorySystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251214213245_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DnDInventorySystem.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("GameId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByUserId = 1,
                            GameId = 1,
                            Name = "Weapons"
                        },
                        new
                        {
                            Id = 2,
                            CreatedByUserId = 1,
                            GameId = 1,
                            Name = "Armor"
                        },
                        new
                        {
                            Id = 3,
                            CreatedByUserId = 1,
                            GameId = 1,
                            Name = "Potions"
                        },
                        new
                        {
                            Id = 4,
                            CreatedByUserId = 1,
                            GameId = 1,
                            Name = "Scrolls"
                        },
                        new
                        {
                            Id = 5,
                            CreatedByUserId = 1,
                            GameId = 1,
                            Name = "Tools"
                        },
                        new
                        {
                            Id = 6,
                            CreatedByUserId = 1,
                            GameId = 1,
                            Name = "Food"
                        },
                        new
                        {
                            Id = 7,
                            CreatedByUserId = 1,
                            GameId = 1,
                            Name = "Trinkets"
                        },
                        new
                        {
                            Id = 8,
                            CreatedByUserId = 1,
                            GameId = 1,
                            Name = "Quest Items"
                        },
                        new
                        {
                            Id = 9,
                            CreatedByUserId = 1,
                            GameId = 1,
                            Name = "Materials"
                        },
                        new
                        {
                            Id = 10,
                            CreatedByUserId = 1,
                            GameId = 1,
                            Name = "Misc"
                        },
                        new
                        {
                            Id = 101,
                            CreatedByUserId = 2,
                            GameId = 2,
                            Name = "Weapons"
                        },
                        new
                        {
                            Id = 102,
                            CreatedByUserId = 2,
                            GameId = 2,
                            Name = "Armor"
                        },
                        new
                        {
                            Id = 103,
                            CreatedByUserId = 2,
                            GameId = 2,
                            Name = "Potions"
                        },
                        new
                        {
                            Id = 104,
                            CreatedByUserId = 2,
                            GameId = 2,
                            Name = "Scrolls"
                        },
                        new
                        {
                            Id = 105,
                            CreatedByUserId = 2,
                            GameId = 2,
                            Name = "Tools"
                        },
                        new
                        {
                            Id = 106,
                            CreatedByUserId = 2,
                            GameId = 2,
                            Name = "Food"
                        },
                        new
                        {
                            Id = 107,
                            CreatedByUserId = 2,
                            GameId = 2,
                            Name = "Trinkets"
                        },
                        new
                        {
                            Id = 108,
                            CreatedByUserId = 2,
                            GameId = 2,
                            Name = "Quest Items"
                        },
                        new
                        {
                            Id = 109,
                            CreatedByUserId = 2,
                            GameId = 2,
                            Name = "Materials"
                        },
                        new
                        {
                            Id = 110,
                            CreatedByUserId = 2,
                            GameId = 2,
                            Name = "Misc"
                        });
                });

            modelBuilder.Entity("DnDInventorySystem.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("GameId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByUserId = 1,
                            Description = "Ranger",
                            GameId = 1,
                            Name = "Aria",
                            OwnerUserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedByUserId = 1,
                            Description = "Cleric",
                            GameId = 1,
                            Name = "Bram",
                            OwnerUserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedByUserId = 1,
                            Description = "Wizard",
                            GameId = 1,
                            Name = "Celeste",
                            OwnerUserId = 1
                        },
                        new
                        {
                            Id = 101,
                            CreatedByUserId = 2,
                            Description = "Fighter",
                            GameId = 2,
                            Name = "Dante",
                            OwnerUserId = 2
                        },
                        new
                        {
                            Id = 102,
                            CreatedByUserId = 2,
                            Description = "Druid",
                            GameId = 2,
                            Name = "Elara",
                            OwnerUserId = 2
                        },
                        new
                        {
                            Id = 103,
                            CreatedByUserId = 2,
                            Description = "Rogue",
                            GameId = 2,
                            Name = "Felix",
                            OwnerUserId = 2
                        });
                });

            modelBuilder.Entity("DnDInventorySystem.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JoinCode")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("JoinCodeActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("JoinCode")
                        .IsUnique()
                        .HasFilter("[JoinCode] IS NOT NULL");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Alice's campaign",
                            JoinCodeActive = false,
                            Name = "Stormreach"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 2,
                            Description = "Bob's campaign",
                            JoinCodeActive = false,
                            Name = "Duskhaven"
                        });
                });

            modelBuilder.Entity("DnDInventorySystem.Models.HistoryLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("GameId");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("HistoryLogs");
                });

            modelBuilder.Entity("DnDInventorySystem.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("GameId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedByUserId = 1,
                            Description = "Longsword description",
                            GameId = 1,
                            Name = "Longsword",
                            PhotoUrl = ""
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedByUserId = 1,
                            Description = "Shield description",
                            GameId = 1,
                            Name = "Shield",
                            PhotoUrl = ""
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedByUserId = 1,
                            Description = "Shortbow description",
                            GameId = 1,
                            Name = "Shortbow",
                            PhotoUrl = ""
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CreatedByUserId = 1,
                            Description = "Dagger description",
                            GameId = 1,
                            Name = "Dagger",
                            PhotoUrl = ""
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            CreatedByUserId = 1,
                            Description = "Quarterstaff description",
                            GameId = 1,
                            Name = "Quarterstaff",
                            PhotoUrl = ""
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            CreatedByUserId = 1,
                            Description = "Healing Potion description",
                            GameId = 1,
                            Name = "Healing Potion",
                            PhotoUrl = ""
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            CreatedByUserId = 1,
                            Description = "Mana Potion description",
                            GameId = 1,
                            Name = "Mana Potion",
                            PhotoUrl = ""
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 8,
                            CreatedByUserId = 1,
                            Description = "Rope description",
                            GameId = 1,
                            Name = "Rope",
                            PhotoUrl = ""
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 9,
                            CreatedByUserId = 1,
                            Description = "Lockpick Set description",
                            GameId = 1,
                            Name = "Lockpick Set",
                            PhotoUrl = ""
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 10,
                            CreatedByUserId = 1,
                            Description = "Torch description",
                            GameId = 1,
                            Name = "Torch",
                            PhotoUrl = ""
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            CreatedByUserId = 1,
                            Description = "Map description",
                            GameId = 1,
                            Name = "Map",
                            PhotoUrl = ""
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            CreatedByUserId = 1,
                            Description = "Silver Ring description",
                            GameId = 1,
                            Name = "Silver Ring",
                            PhotoUrl = ""
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            CreatedByUserId = 1,
                            Description = "Chain Shirt description",
                            GameId = 1,
                            Name = "Chain Shirt",
                            PhotoUrl = ""
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            CreatedByUserId = 1,
                            Description = "Bag of Holding description",
                            GameId = 1,
                            Name = "Bag of Holding",
                            PhotoUrl = ""
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            CreatedByUserId = 1,
                            Description = "Scroll of Fireball description",
                            GameId = 1,
                            Name = "Scroll of Fireball",
                            PhotoUrl = ""
                        },
                        new
                        {
                            Id = 101,
                            CategoryId = 101,
                            CreatedByUserId = 2,
                            Description = "Battleaxe description",
                            GameId = 2,
                            Name = "Battleaxe",
                            PhotoUrl = ""
                        },
                        new
                        {
                            Id = 102,
                            CategoryId = 102,
                            CreatedByUserId = 2,
                            Description = "Buckler description",
                            GameId = 2,
                            Name = "Buckler",
                            PhotoUrl = ""
                        },
                        new
                        {
                            Id = 103,
                            CategoryId = 103,
                            CreatedByUserId = 2,
                            Description = "Crossbow description",
                            GameId = 2,
                            Name = "Crossbow",
                            PhotoUrl = ""
                        },
                        new
                        {
                            Id = 104,
                            CategoryId = 104,
                            CreatedByUserId = 2,
                            Description = "Stiletto description",
                            GameId = 2,
                            Name = "Stiletto",
                            PhotoUrl = ""
                        },
                        new
                        {
                            Id = 105,
                            CategoryId = 105,
                            CreatedByUserId = 2,
                            Description = "Wand description",
                            GameId = 2,
                            Name = "Wand",
                            PhotoUrl = ""
                        },
                        new
                        {
                            Id = 106,
                            CategoryId = 106,
                            CreatedByUserId = 2,
                            Description = "Elixir of Health description",
                            GameId = 2,
                            Name = "Elixir of Health",
                            PhotoUrl = ""
                        },
                        new
                        {
                            Id = 107,
                            CategoryId = 107,
                            CreatedByUserId = 2,
                            Description = "Stamina Draught description",
                            GameId = 2,
                            Name = "Stamina Draught",
                            PhotoUrl = ""
                        },
                        new
                        {
                            Id = 108,
                            CategoryId = 108,
                            CreatedByUserId = 2,
                            Description = "Grappling Hook description",
                            GameId = 2,
                            Name = "Grappling Hook",
                            PhotoUrl = ""
                        },
                        new
                        {
                            Id = 109,
                            CategoryId = 109,
                            CreatedByUserId = 2,
                            Description = "Thieves' Tools description",
                            GameId = 2,
                            Name = "Thieves' Tools",
                            PhotoUrl = ""
                        },
                        new
                        {
                            Id = 110,
                            CategoryId = 110,
                            CreatedByUserId = 2,
                            Description = "Lantern description",
                            GameId = 2,
                            Name = "Lantern",
                            PhotoUrl = ""
                        },
                        new
                        {
                            Id = 111,
                            CategoryId = 101,
                            CreatedByUserId = 2,
                            Description = "Compass description",
                            GameId = 2,
                            Name = "Compass",
                            PhotoUrl = ""
                        },
                        new
                        {
                            Id = 112,
                            CategoryId = 102,
                            CreatedByUserId = 2,
                            Description = "Gold Amulet description",
                            GameId = 2,
                            Name = "Gold Amulet",
                            PhotoUrl = ""
                        },
                        new
                        {
                            Id = 113,
                            CategoryId = 103,
                            CreatedByUserId = 2,
                            Description = "Scale Mail description",
                            GameId = 2,
                            Name = "Scale Mail",
                            PhotoUrl = ""
                        },
                        new
                        {
                            Id = 114,
                            CategoryId = 104,
                            CreatedByUserId = 2,
                            Description = "Handy Haversack description",
                            GameId = 2,
                            Name = "Handy Haversack",
                            PhotoUrl = ""
                        },
                        new
                        {
                            Id = 115,
                            CategoryId = 105,
                            CreatedByUserId = 2,
                            Description = "Scroll of Lightning description",
                            GameId = 2,
                            Name = "Scroll of Lightning",
                            PhotoUrl = ""
                        });
                });

            modelBuilder.Entity("DnDInventorySystem.Models.ItemCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("bit");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("CharacterId", "ItemId")
                        .IsUnique();

                    b.ToTable("ItemCharacters");
                });

            modelBuilder.Entity("DnDInventorySystem.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DnDInventorySystem.Models.RolePerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("RolePersons");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice@example.com",
                            Name = "Alice",
                            PasswordHash = "Password123!"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob@example.com",
                            Name = "Bob",
                            PasswordHash = "Swordfish1!"
                        });
                });

            modelBuilder.Entity("DnDInventorySystem.Models.Category", b =>
                {
                    b.HasOne("User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DnDInventorySystem.Models.Game", "Game")
                        .WithMany("Categories")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("DnDInventorySystem.Models.Character", b =>
                {
                    b.HasOne("User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DnDInventorySystem.Models.Game", "Game")
                        .WithMany("Characters")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Game");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DnDInventorySystem.Models.Game", b =>
                {
                    b.HasOne("User", "CreatedByUser")
                        .WithMany("CreatedGames")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("DnDInventorySystem.Models.HistoryLog", b =>
                {
                    b.HasOne("DnDInventorySystem.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DnDInventorySystem.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DnDInventorySystem.Models.Game", "Game")
                        .WithMany("HistoryLogs")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDInventorySystem.Models.Item", "Item")
                        .WithMany("HistoryLogs")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Character");

                    b.Navigation("Game");

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DnDInventorySystem.Models.Item", b =>
                {
                    b.HasOne("DnDInventorySystem.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DnDInventorySystem.Models.Game", "Game")
                        .WithMany("Items")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("DnDInventorySystem.Models.ItemCharacter", b =>
                {
                    b.HasOne("DnDInventorySystem.Models.Character", "Character")
                        .WithMany("ItemCharacters")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DnDInventorySystem.Models.Item", "Item")
                        .WithMany("ItemCharacters")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("DnDInventorySystem.Models.RolePerson", b =>
                {
                    b.HasOne("DnDInventorySystem.Models.Game", "Game")
                        .WithMany("RolePersons")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DnDInventorySystem.Models.Role", "Role")
                        .WithMany("RolePersons")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DnDInventorySystem.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DnDInventorySystem.Models.Character", b =>
                {
                    b.Navigation("ItemCharacters");
                });

            modelBuilder.Entity("DnDInventorySystem.Models.Game", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Characters");

                    b.Navigation("HistoryLogs");

                    b.Navigation("Items");

                    b.Navigation("RolePersons");
                });

            modelBuilder.Entity("DnDInventorySystem.Models.Item", b =>
                {
                    b.Navigation("HistoryLogs");

                    b.Navigation("ItemCharacters");
                });

            modelBuilder.Entity("DnDInventorySystem.Models.Role", b =>
                {
                    b.Navigation("RolePersons");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("CreatedGames");
                });
#pragma warning restore 612, 618
        }
    }
}
